#  Template Java Gradle build

#  This template allows you to test and build your Java project with Gradle.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: appropriate project structure should exist in the repository.

image: gradle:8.2.0

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test Backend
          caches:
            - gradle
          script:
            - cd server/MovieSocialNetwork
            - gradle build
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Client Build
          image: node:20-alpine
          script:
            - cd ./client/
            - npm install
            - npm run build
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Client Test
          image: node:20-alpine
          script:
            - apk add chromium
            - export CHROME_BIN=/usr/bin/chromium-browser
            - cd ./client/
            - npm install
            - ./node_modules/.bin/ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0
    - step:
        name: Security Scan
        script:
          # Run a security scan for sensitive data.
          # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
          - pipe: atlassian/git-secrets-scan:0.5.1