version: '3.8'

services:
  # Angular Frontend
  angular-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    ports:
      - "4200:80" # Host:Container

  # Kotlin Backend
  kotlin-backend:
    build:
      context: ./server/MovieSocialNetwork
      dockerfile: Dockerfile
    image: server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: sep6
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - postgres-db

  # PostgreSQL Database
  postgres-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
